[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.5",
    "opencv-python>=4.11.0.86",
    "pyautogui>=0.9.54",
    "pyinstaller>=6.13.0",
    "pyqt5>=5.15.11",
]
